controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # List of controllers to load at startup
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    authentic_lite6_gripper_controller:
      type: position_controllers/GripperActionController
      
    vacuum_controller:
      type: position_controllers/JointPositionController

# Arm controller configuration for real hardware
arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2  
      - joint3
      - joint4
      - joint5
      - joint6
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
      - effort
    
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.05  # More tolerance for real hardware
      goal_time: 1.0  # More time for real hardware
      joint1: { trajectory: 0.1, goal: 0.05 }
      joint2: { trajectory: 0.1, goal: 0.05 }
      joint3: { trajectory: 0.1, goal: 0.05 }
      joint4: { trajectory: 0.1, goal: 0.05 }
      joint5: { trajectory: 0.1, goal: 0.05 }
      joint6: { trajectory: 0.1, goal: 0.05 }

# Authentic Lite6 Gripper controller configuration for real hardware
authentic_lite6_gripper_controller:
  ros__parameters:
    joint: lite6_left_finger_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.02  # Slightly more tolerance for real hardware
    max_effort: 15.0  # Higher effort for real hardware
    allow_stalling: true
    stall_velocity_threshold: 0.01
    stall_timeout: 2.0

# Vacuum controller configuration for real hardware
vacuum_controller:
  ros__parameters:
    joint: vacuum_joint
    interface_name: position