controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    # List of controllers to load at startup
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    authentic_lite6_gripper_controller:
      type: position_controllers/GripperActionController

# Arm controller configuration
arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2  
      - joint3
      - joint4
      - joint5
      - joint6
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1: { trajectory: 0.05, goal: 0.03 }
      joint2: { trajectory: 0.05, goal: 0.03 }
      joint3: { trajectory: 0.05, goal: 0.03 }
      joint4: { trajectory: 0.05, goal: 0.03 }
      joint5: { trajectory: 0.05, goal: 0.03 }
      joint6: { trajectory: 0.05, goal: 0.03 }

# Authentic Lite6 Gripper controller configuration
authentic_lite6_gripper_controller:
  ros__parameters:
    joint: lite6_left_finger_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 10.0
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0